services:
  - type: web
    name: jobfilter-app
    env: docker
    plan: free
    healthCheckPath: /
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: LOG_CHANNEL
        value: stderr
      - key: DB_CONNECTION
        value: pgsql
      - key: QUEUE_CONNECTION
        value: sync
      - key: SESSION_DRIVER
        value: cookie
      - key: CACHE_DRIVER
        value: file
      - fromGroup: jobfilter-env
    buildCommand: composer install && php artisan migrate --force && npm install && npm run build
    startCommand: php artisan serve --host=0.0.0.0 --port=$PORT

  - type: pserv
    name: jobfilter-db
    env: docker
    plan: free
    ipAllowList: []
    envVars:
      - key: POSTGRES_DB
        value: jobfilter
      - key: POSTGRES_USER
        value: postgres
      - fromGroup: jobfilter-db-env

envVarGroups:
  - name: jobfilter-env
    envVars:
      - key: APP_KEY
        sync: false
      - key: DB_HOST
        value: jobfilter-db
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: jobfilter
      - key: DB_USERNAME
        value: postgres
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: SUPABASE_SECRET_KEY
        sync: false

  - name: jobfilter-db-env
    envVars:
      - key: POSTGRES_PASSWORD
        sync: false
